FROM php:8.2-apache
RUN apt update && apt install -y libicu-dev
RUN docker-php-ext-install intl mysqli
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
RUN chown -R www-data:www-data /var/www/html
EXPOSE 80
CMD ["apache2-foreground"]
